### ISSUE TITLE
EA on dedicated server

### ISSUE THREAD

**Issue by jriwanek** [cyanobacterium/ElectricAdvantage#9]
[05:40:56] [Server thread/ERROR] [FML/]: A TileEntity electricadvantage.electric_still(cyano.electricadvantage.machines.ElectricStillTileEntity) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.ArrayIndexOutOfBoundsException: 1
        at cyano.poweradvantage.api.simple.TileEntitySimplePowerMachine.setEnergy(TileEntitySimplePowerMachine.java:373) ~[TileEntitySimplePowerMachine.class:?]
        at cyano.poweradvantage.api.PoweredEntity.func_145839_a(PoweredEntity.java:184) ~[PoweredEntity.class:?]
        at cyano.poweradvantage.api.simple.TileEntitySimplePowerMachine.func_145839_a(TileEntitySimplePowerMachine.java:293) ~[TileEntitySimplePowerMachine.class:?]
        at cyano.electricadvantage.machines.ElectricMachineTileEntity.func_145839_a(ElectricMachineTileEntity.java:205) ~[ElectricMachineTileEntity.class:?]
        at net.minecraft.tileentity.TileEntity.func_184246_b(TileEntity.java:113) [apv.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:452) [ass.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:75) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:71) [ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:121) [lo.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:96) [lo.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:295) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:265) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:264) [la.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by DrPlantabyte** [comment]
I think I found the bug. Should be fixed in next release.
